project:
  type: website

website:
  title: "Automated Website - Weekly Top Artists"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: music-automated-report.qmd
        text: Weekly Top Artists
      - href: about.qmd
        text: About

format:
  html:
    theme: darkly # Use the Darkly theme for a sleek, modern dark mode
    fontsize: 1.3em # Increase the base font size for better readability
    fontcolor: "#e0e0e0" # Use a light gray color for text to contrast with the dark background
    backgroundcolor: "#121212" # Set a very dark background color
    linkcolor: "#76c7c0" # Use a soft teal color for links to stand out against the dark background
    mainfont: "Helvetica, sans-serif" # Use a clean sans-serif font for the main text
    monofont: "Monaco, monospace" # Use Monaco for code elements for a techy feel
    monobackgroundcolor: "#333333" # Set a dark gray background for code elements
    linestretch: 1.7 # Maintain good line spacing for readability
    margin-left: 2.5em # Adjust margins to fit the darker theme layout
    margin-right: 2.5em
    margin-top: 2.5em
    margin-bottom: 2.5em
    toc: true # Include a table of contents for easy navigation
    code-block-bg: "#1a1a1a" # Set the background for code blocks to a darker shade
    code-block-border-left: "#76c7c0" # Add a teal left border to code blocks for a stylish touch


